import CatalogList from "@/components/CatalogList";

const catagories = [
    {
        name: "vòng tay",
        id: 1,
        banner: "https://cdn.pnj.io/images/promo/191/kimcuong-t11-1200x450CTA.jpg",
        src: "https://cdn.pnj.io/images/thumbnails/300/300/detailed/193/sp-glxmxmy000993-lac-tay-vang-14k-dinh-da-cz-pnj-01.png",
        product: [
            {
                id: 9,
                name: "Dây chuyền kim cương",
                code: "DAYCHUYEN003",
                images: "https://cdn.pnj.io/images/thumbnails/300/300/detailed/193/sp-gbxmxmy006144-bong-tai-vang-14k-dinh-da-cz-pnj-01.png",
                origin: "USA",
                material: "Kim cương",
                size: "40cm",
                warranty: "Lifetime",
                description: "Dây chuyền kim cương cao cấp, bền vững.",
                price: 499,
                category: "Dây chuyền",
                inventory: 5,
                createdAt: "2023-11-30T21:51:36.000Z",
                updatedAt: "2023-11-30T21:51:36.000Z",
                deletedAt: null,
            },
            {
                id: 1,
                name: "Vòng tay đá xanh",
                code: "VONGTAY001",
                images: "https://cdn.pnj.io/images/thumbnails/300/300/detailed/193/sp-glxmxmy000993-lac-tay-vang-14k-dinh-da-cz-pnj-01.png",
                origin: "Vietnam",
                material: "Đá",
                size: "Free size",
                warranty: "6 months",
                description: "Vòng tay đá xanh dành cho mọi lứa tuổi.",
                price: 25,
                category: "Vòng tay",
                inventory: 1,
                createdAt: "2023-11-30T21:51:36.000Z",
                updatedAt: "2023-11-30T21:51:36.000Z",
                deletedAt: null,
            },
            {
                id: 7,
                name: "Dây chuyền vàng hồng",
                code: "DAYCHUYEN001",
                images: "https://cdn.pnj.io/images/thumbnails/300/300/detailed/193/sp-glxmxmy000997-lac-tay-vang-14k-dinh-da-cz-pnj-01.png",
                origin: "France",
                material: "Vàng hồng 14K",
                size: "45cm",
                warranty: "1 year",
                description: "Dây chuyền vàng hồng 14K đẳng cấp.",
                price: 149,
                category: "Dây chuyền",
                inventory: 75,
                createdAt: "2023-11-30T21:51:36.000Z",
                updatedAt: "2023-11-30T21:51:36.000Z",
                deletedAt: null,
            },
            {
                id: 6,
                code: "KHUYENTAI",
                name: "Khuyên tai lấp lánh",
                images: "https://cdn.pnj.io/images/thumbnails/300/300/detailed/192/sp-gcxmxmw000391-day-co-vang-14k-dinh-da-ecz-disney-pnj-snow-white-the-seven-dwarfs-d100-1.png",
                origin: "VN",
                material: "Kim cương",
                size: "nhỏ 4x6",
                warranty: "1 năm",
                description: "Khuyên tai lấp lánh phù hợp cho mọi lứa tuổi",
                price: 10,
                categoryId: 1,
                quantity: 10,
                discountId: 0,
            },
            {
                id: 5,
                name: "Dây chuyền kim cương",
                code: "DAYCHUYEN003",
                images: "https://cdn.pnj.io/images/thumbnails/300/300/detailed/193/sp-gbxmxmy006144-bong-tai-vang-14k-dinh-da-cz-pnj-01.png",
                origin: "USA",
                material: "Kim cương",
                size: "40cm",
                warranty: "Lifetime",
                description: "Dây chuyền kim cương cao cấp, bền vững.",
                price: 499,
                category: "Dây chuyền",
                inventory: 5,
                createdAt: "2023-11-30T21:51:36.000Z",
                updatedAt: "2023-11-30T21:51:36.000Z",
                deletedAt: null,
            },
            {
                id: 4,
                name: "Vòng tay đá xanh",
                code: "VONGTAY001",
                images: "https://cdn.pnj.io/images/thumbnails/300/300/detailed/193/sp-glxmxmy000993-lac-tay-vang-14k-dinh-da-cz-pnj-01.png",
                origin: "Vietnam",
                material: "Đá",
                size: "Free size",
                warranty: "6 months",
                description: "Vòng tay đá xanh dành cho mọi lứa tuổi.",
                price: 25,
                category: "Vòng tay",
                inventory: 1,
                createdAt: "2023-11-30T21:51:36.000Z",
                updatedAt: "2023-11-30T21:51:36.000Z",
                deletedAt: null,
            },
            {
                id: 8,
                name: "Dây chuyền vàng hồng",
                code: "DAYCHUYEN001",
                images: "https://cdn.pnj.io/images/thumbnails/300/300/detailed/192/sp-gv0000w060419-vong-tay-vang-trang-y-18k-pnj-1.png",
                origin: "France",
                material: "Vàng hồng 14K",
                size: "45cm",
                warranty: "1 year",
                description: "Dây chuyền vàng hồng 14K đẳng cấp.",
                price: 149,
                category: "Dây chuyền",
                inventory: 75,
                createdAt: "2023-11-30T21:51:36.000Z",
                updatedAt: "2023-11-30T21:51:36.000Z",
                deletedAt: null,
            },
            {
                id: 3,
                code: "KHUYENTAI",
                name: "Khuyên tai lấp lánh",
                images: "https://cdn.pnj.io/images/thumbnails/300/300/detailed/192/sp-gnxmxmw004435-nhan-vang-14k-dinh-da-ecz-disney-pnj-general-disney-princess-d100-1.png",
                origin: "VN",
                material: "Kim cương",
                size: "nhỏ 4x6",
                warranty: "1 năm",
                description: "Khuyên tai lấp lánh phù hợp cho mọi lứa tuổi",
                price: 10,
                categoryId: 1,
                quantity: 10,
                discountId: 0,
            },
            {
                id: 2,
                code: "KHUYENTAI",
                name: "Khuyên tai lấp lánh",
                images: "https://cdn.pnj.io/images/thumbnails/300/300/detailed/192/sp-gnxmxmw004434-nhan-vang-14k-dinh-da-ecz-disney-pnj-snow-white-the-seven-dwarfs-d100-1.png",
                origin: "VN",
                material: "Kim cương",
                size: "nhỏ 4x6",
                warranty: "1 năm",
                description: "Khuyên tai lấp lánh phù hợp cho mọi lứa tuổi",
                price: 10,
                categoryId: 1,
                quantity: 10,
                discountId: 0,
            },
        ],
    },
    {
        name: "nhẫn",
        id: 2,
        banner: "https://cdn.pnj.io/images/promo/191/day-chuyen-t11-1200x450-CTA.jpg",
        src: "https://cdn.pnj.io/images/thumbnails/300/300/detailed/193/sp-glxmxmy000993-lac-tay-vang-14k-dinh-da-cz-pnj-01.png",
        product: [
            {
                id: 9,
                name: "Dây chuyền kim cương",
                code: "DAYCHUYEN003",
                images: "https://cdn.pnj.io/images/thumbnails/300/300/detailed/193/sp-gbxmxmy006144-bong-tai-vang-14k-dinh-da-cz-pnj-01.png",
                origin: "USA",
                material: "Kim cương",
                size: "40cm",
                warranty: "Lifetime",
                description: "Dây chuyền kim cương cao cấp, bền vững.",
                price: 499,
                category: "Dây chuyền",
                inventory: 5,
                createdAt: "2023-11-30T21:51:36.000Z",
                updatedAt: "2023-11-30T21:51:36.000Z",
                deletedAt: null,
            },
            {
                id: 1,
                name: "Vòng tay đá xanh",
                code: "VONGTAY001",
                images: "https://cdn.pnj.io/images/thumbnails/300/300/detailed/193/sp-glxmxmy000993-lac-tay-vang-14k-dinh-da-cz-pnj-01.png",
                origin: "Vietnam",
                material: "Đá",
                size: "Free size",
                warranty: "6 months",
                description: "Vòng tay đá xanh dành cho mọi lứa tuổi.",
                price: 25,
                category: "Vòng tay",
                inventory: 1,
                createdAt: "2023-11-30T21:51:36.000Z",
                updatedAt: "2023-11-30T21:51:36.000Z",
                deletedAt: null,
            },
            {
                id: 7,
                name: "Dây chuyền vàng hồng",
                code: "DAYCHUYEN001",
                images: "https://cdn.pnj.io/images/thumbnails/300/300/detailed/193/sp-glxmxmy000997-lac-tay-vang-14k-dinh-da-cz-pnj-01.png",
                origin: "France",
                material: "Vàng hồng 14K",
                size: "45cm",
                warranty: "1 year",
                description: "Dây chuyền vàng hồng 14K đẳng cấp.",
                price: 149,
                category: "Dây chuyền",
                inventory: 75,
                createdAt: "2023-11-30T21:51:36.000Z",
                updatedAt: "2023-11-30T21:51:36.000Z",
                deletedAt: null,
            },
            {
                id: 6,
                code: "KHUYENTAI",
                name: "Khuyên tai lấp lánh",
                images: "https://cdn.pnj.io/images/thumbnails/300/300/detailed/192/sp-gcxmxmw000391-day-co-vang-14k-dinh-da-ecz-disney-pnj-snow-white-the-seven-dwarfs-d100-1.png",
                origin: "VN",
                material: "Kim cương",
                size: "nhỏ 4x6",
                warranty: "1 năm",
                description: "Khuyên tai lấp lánh phù hợp cho mọi lứa tuổi",
                price: 10,
                categoryId: 1,
                quantity: 10,
                discountId: 0,
            },
            {
                id: 5,
                name: "Dây chuyền kim cương",
                code: "DAYCHUYEN003",
                images: "https://cdn.pnj.io/images/thumbnails/300/300/detailed/193/sp-gbxmxmy006144-bong-tai-vang-14k-dinh-da-cz-pnj-01.png",
                origin: "USA",
                material: "Kim cương",
                size: "40cm",
                warranty: "Lifetime",
                description: "Dây chuyền kim cương cao cấp, bền vững.",
                price: 499,
                category: "Dây chuyền",
                inventory: 5,
                createdAt: "2023-11-30T21:51:36.000Z",
                updatedAt: "2023-11-30T21:51:36.000Z",
                deletedAt: null,
            },
            {
                id: 4,
                name: "Vòng tay đá xanh",
                code: "VONGTAY001",
                images: "https://cdn.pnj.io/images/thumbnails/300/300/detailed/193/sp-glxmxmy000993-lac-tay-vang-14k-dinh-da-cz-pnj-01.png",
                origin: "Vietnam",
                material: "Đá",
                size: "Free size",
                warranty: "6 months",
                description: "Vòng tay đá xanh dành cho mọi lứa tuổi.",
                price: 25,
                category: "Vòng tay",
                inventory: 1,
                createdAt: "2023-11-30T21:51:36.000Z",
                updatedAt: "2023-11-30T21:51:36.000Z",
                deletedAt: null,
            },
            {
                id: 8,
                name: "Dây chuyền vàng hồng",
                code: "DAYCHUYEN001",
                images: "https://cdn.pnj.io/images/thumbnails/300/300/detailed/192/sp-gv0000w060419-vong-tay-vang-trang-y-18k-pnj-1.png",
                origin: "France",
                material: "Vàng hồng 14K",
                size: "45cm",
                warranty: "1 year",
                description: "Dây chuyền vàng hồng 14K đẳng cấp.",
                price: 149,
                category: "Dây chuyền",
                inventory: 75,
                createdAt: "2023-11-30T21:51:36.000Z",
                updatedAt: "2023-11-30T21:51:36.000Z",
                deletedAt: null,
            },
            {
                id: 3,
                code: "KHUYENTAI",
                name: "Khuyên tai lấp lánh",
                images: "https://cdn.pnj.io/images/thumbnails/300/300/detailed/192/sp-gnxmxmw004435-nhan-vang-14k-dinh-da-ecz-disney-pnj-general-disney-princess-d100-1.png",
                origin: "VN",
                material: "Kim cương",
                size: "nhỏ 4x6",
                warranty: "1 năm",
                description: "Khuyên tai lấp lánh phù hợp cho mọi lứa tuổi",
                price: 10,
                categoryId: 1,
                quantity: 10,
                discountId: 0,
            },
            {
                id: 2,
                code: "KHUYENTAI",
                name: "Khuyên tai lấp lánh",
                images: "https://cdn.pnj.io/images/thumbnails/300/300/detailed/192/sp-gnxmxmw004434-nhan-vang-14k-dinh-da-ecz-disney-pnj-snow-white-the-seven-dwarfs-d100-1.png",
                origin: "VN",
                material: "Kim cương",
                size: "nhỏ 4x6",
                warranty: "1 năm",
                description: "Khuyên tai lấp lánh phù hợp cho mọi lứa tuổi",
                price: 10,
                categoryId: 1,
                quantity: 10,
                discountId: 0,
            },
        ],
    },
    {
        name: "lắc chân",
        id: 3,
        banner: "https://cdn.pnj.io/images/promo/187/phong-thuy-t10-1200x450-CTA.jpg",
        src: "https://cdn.pnj.io/images/thumbnails/300/300/detailed/193/sp-glxmxmy000993-lac-tay-vang-14k-dinh-da-cz-pnj-01.png",
        product: [
            {
                id: 9,
                name: "Dây chuyền kim cương",
                code: "DAYCHUYEN003",
                images: "https://cdn.pnj.io/images/thumbnails/300/300/detailed/193/sp-gbxmxmy006144-bong-tai-vang-14k-dinh-da-cz-pnj-01.png",
                origin: "USA",
                material: "Kim cương",
                size: "40cm",
                warranty: "Lifetime",
                description: "Dây chuyền kim cương cao cấp, bền vững.",
                price: 499,
                category: "Dây chuyền",
                inventory: 5,
                createdAt: "2023-11-30T21:51:36.000Z",
                updatedAt: "2023-11-30T21:51:36.000Z",
                deletedAt: null,
            },
            {
                id: 1,
                name: "Vòng tay đá xanh",
                code: "VONGTAY001",
                images: "https://cdn.pnj.io/images/thumbnails/300/300/detailed/193/sp-glxmxmy000993-lac-tay-vang-14k-dinh-da-cz-pnj-01.png",
                origin: "Vietnam",
                material: "Đá",
                size: "Free size",
                warranty: "6 months",
                description: "Vòng tay đá xanh dành cho mọi lứa tuổi.",
                price: 25,
                category: "Vòng tay",
                inventory: 1,
                createdAt: "2023-11-30T21:51:36.000Z",
                updatedAt: "2023-11-30T21:51:36.000Z",
                deletedAt: null,
            },
            {
                id: 7,
                name: "Dây chuyền vàng hồng",
                code: "DAYCHUYEN001",
                images: "https://cdn.pnj.io/images/thumbnails/300/300/detailed/193/sp-glxmxmy000997-lac-tay-vang-14k-dinh-da-cz-pnj-01.png",
                origin: "France",
                material: "Vàng hồng 14K",
                size: "45cm",
                warranty: "1 year",
                description: "Dây chuyền vàng hồng 14K đẳng cấp.",
                price: 149,
                category: "Dây chuyền",
                inventory: 75,
                createdAt: "2023-11-30T21:51:36.000Z",
                updatedAt: "2023-11-30T21:51:36.000Z",
                deletedAt: null,
            },
            {
                id: 6,
                code: "KHUYENTAI",
                name: "Khuyên tai lấp lánh",
                images: "https://cdn.pnj.io/images/thumbnails/300/300/detailed/192/sp-gcxmxmw000391-day-co-vang-14k-dinh-da-ecz-disney-pnj-snow-white-the-seven-dwarfs-d100-1.png",
                origin: "VN",
                material: "Kim cương",
                size: "nhỏ 4x6",
                warranty: "1 năm",
                description: "Khuyên tai lấp lánh phù hợp cho mọi lứa tuổi",
                price: 10,
                categoryId: 1,
                quantity: 10,
                discountId: 0,
            },
            {
                id: 5,
                name: "Dây chuyền kim cương",
                code: "DAYCHUYEN003",
                images: "https://cdn.pnj.io/images/thumbnails/300/300/detailed/193/sp-gbxmxmy006144-bong-tai-vang-14k-dinh-da-cz-pnj-01.png",
                origin: "USA",
                material: "Kim cương",
                size: "40cm",
                warranty: "Lifetime",
                description: "Dây chuyền kim cương cao cấp, bền vững.",
                price: 499,
                category: "Dây chuyền",
                inventory: 5,
                createdAt: "2023-11-30T21:51:36.000Z",
                updatedAt: "2023-11-30T21:51:36.000Z",
                deletedAt: null,
            },
            {
                id: 4,
                name: "Vòng tay đá xanh",
                code: "VONGTAY001",
                images: "https://cdn.pnj.io/images/thumbnails/300/300/detailed/193/sp-glxmxmy000993-lac-tay-vang-14k-dinh-da-cz-pnj-01.png",
                origin: "Vietnam",
                material: "Đá",
                size: "Free size",
                warranty: "6 months",
                description: "Vòng tay đá xanh dành cho mọi lứa tuổi.",
                price: 25,
                category: "Vòng tay",
                inventory: 1,
                createdAt: "2023-11-30T21:51:36.000Z",
                updatedAt: "2023-11-30T21:51:36.000Z",
                deletedAt: null,
            },
            {
                id: 8,
                name: "Dây chuyền vàng hồng",
                code: "DAYCHUYEN001",
                images: "https://cdn.pnj.io/images/thumbnails/300/300/detailed/192/sp-gv0000w060419-vong-tay-vang-trang-y-18k-pnj-1.png",
                origin: "France",
                material: "Vàng hồng 14K",
                size: "45cm",
                warranty: "1 year",
                description: "Dây chuyền vàng hồng 14K đẳng cấp.",
                price: 149,
                category: "Dây chuyền",
                inventory: 75,
                createdAt: "2023-11-30T21:51:36.000Z",
                updatedAt: "2023-11-30T21:51:36.000Z",
                deletedAt: null,
            },
            {
                id: 3,
                code: "KHUYENTAI",
                name: "Khuyên tai lấp lánh",
                images: "https://cdn.pnj.io/images/thumbnails/300/300/detailed/192/sp-gnxmxmw004435-nhan-vang-14k-dinh-da-ecz-disney-pnj-general-disney-princess-d100-1.png",
                origin: "VN",
                material: "Kim cương",
                size: "nhỏ 4x6",
                warranty: "1 năm",
                description: "Khuyên tai lấp lánh phù hợp cho mọi lứa tuổi",
                price: 10,
                categoryId: 1,
                quantity: 10,
                discountId: 0,
            },
            {
                id: 2,
                code: "KHUYENTAI",
                name: "Khuyên tai lấp lánh",
                images: "https://cdn.pnj.io/images/thumbnails/300/300/detailed/192/sp-gnxmxmw004434-nhan-vang-14k-dinh-da-ecz-disney-pnj-snow-white-the-seven-dwarfs-d100-1.png",
                origin: "VN",
                material: "Kim cương",
                size: "nhỏ 4x6",
                warranty: "1 năm",
                description: "Khuyên tai lấp lánh phù hợp cho mọi lứa tuổi",
                price: 10,
                categoryId: 1,
                quantity: 10,
                discountId: 0,
            },
        ],
    },
    {
        name: "dây chuyền",
        id: 4,
        banner: "https://cdn.pnj.io/images/promo/195/disney-t12-1200X450CTA__8_.jpg",
        src: "https://cdn.pnj.io/images/thumbnails/300/300/detailed/193/sp-glxmxmy000993-lac-tay-vang-14k-dinh-da-cz-pnj-01.png",
        product: [
            {
                id: 9,
                name: "Dây chuyền kim cương",
                code: "DAYCHUYEN003",
                images: "https://cdn.pnj.io/images/thumbnails/300/300/detailed/193/sp-gbxmxmy006144-bong-tai-vang-14k-dinh-da-cz-pnj-01.png",
                origin: "USA",
                material: "Kim cương",
                size: "40cm",
                warranty: "Lifetime",
                description: "Dây chuyền kim cương cao cấp, bền vững.",
                price: 499,
                category: "Dây chuyền",
                inventory: 5,
                createdAt: "2023-11-30T21:51:36.000Z",
                updatedAt: "2023-11-30T21:51:36.000Z",
                deletedAt: null,
            },
            {
                id: 1,
                name: "Vòng tay đá xanh",
                code: "VONGTAY001",
                images: "https://cdn.pnj.io/images/thumbnails/300/300/detailed/193/sp-glxmxmy000993-lac-tay-vang-14k-dinh-da-cz-pnj-01.png",
                origin: "Vietnam",
                material: "Đá",
                size: "Free size",
                warranty: "6 months",
                description: "Vòng tay đá xanh dành cho mọi lứa tuổi.",
                price: 25,
                category: "Vòng tay",
                inventory: 1,
                createdAt: "2023-11-30T21:51:36.000Z",
                updatedAt: "2023-11-30T21:51:36.000Z",
                deletedAt: null,
            },
            {
                id: 7,
                name: "Dây chuyền vàng hồng",
                code: "DAYCHUYEN001",
                images: "https://cdn.pnj.io/images/thumbnails/300/300/detailed/193/sp-glxmxmy000997-lac-tay-vang-14k-dinh-da-cz-pnj-01.png",
                origin: "France",
                material: "Vàng hồng 14K",
                size: "45cm",
                warranty: "1 year",
                description: "Dây chuyền vàng hồng 14K đẳng cấp.",
                price: 149,
                category: "Dây chuyền",
                inventory: 75,
                createdAt: "2023-11-30T21:51:36.000Z",
                updatedAt: "2023-11-30T21:51:36.000Z",
                deletedAt: null,
            },
            {
                id: 6,
                code: "KHUYENTAI",
                name: "Khuyên tai lấp lánh",
                images: "https://cdn.pnj.io/images/thumbnails/300/300/detailed/192/sp-gcxmxmw000391-day-co-vang-14k-dinh-da-ecz-disney-pnj-snow-white-the-seven-dwarfs-d100-1.png",
                origin: "VN",
                material: "Kim cương",
                size: "nhỏ 4x6",
                warranty: "1 năm",
                description: "Khuyên tai lấp lánh phù hợp cho mọi lứa tuổi",
                price: 10,
                categoryId: 1,
                quantity: 10,
                discountId: 0,
            },
            {
                id: 5,
                name: "Dây chuyền kim cương",
                code: "DAYCHUYEN003",
                images: "https://cdn.pnj.io/images/thumbnails/300/300/detailed/193/sp-gbxmxmy006144-bong-tai-vang-14k-dinh-da-cz-pnj-01.png",
                origin: "USA",
                material: "Kim cương",
                size: "40cm",
                warranty: "Lifetime",
                description: "Dây chuyền kim cương cao cấp, bền vững.",
                price: 499,
                category: "Dây chuyền",
                inventory: 5,
                createdAt: "2023-11-30T21:51:36.000Z",
                updatedAt: "2023-11-30T21:51:36.000Z",
                deletedAt: null,
            },
            {
                id: 4,
                name: "Vòng tay đá xanh",
                code: "VONGTAY001",
                images: "https://cdn.pnj.io/images/thumbnails/300/300/detailed/193/sp-glxmxmy000993-lac-tay-vang-14k-dinh-da-cz-pnj-01.png",
                origin: "Vietnam",
                material: "Đá",
                size: "Free size",
                warranty: "6 months",
                description: "Vòng tay đá xanh dành cho mọi lứa tuổi.",
                price: 25,
                category: "Vòng tay",
                inventory: 1,
                createdAt: "2023-11-30T21:51:36.000Z",
                updatedAt: "2023-11-30T21:51:36.000Z",
                deletedAt: null,
            },
            {
                id: 8,
                name: "Dây chuyền vàng hồng",
                code: "DAYCHUYEN001",
                images: "https://cdn.pnj.io/images/thumbnails/300/300/detailed/192/sp-gv0000w060419-vong-tay-vang-trang-y-18k-pnj-1.png",
                origin: "France",
                material: "Vàng hồng 14K",
                size: "45cm",
                warranty: "1 year",
                description: "Dây chuyền vàng hồng 14K đẳng cấp.",
                price: 149,
                category: "Dây chuyền",
                inventory: 75,
                createdAt: "2023-11-30T21:51:36.000Z",
                updatedAt: "2023-11-30T21:51:36.000Z",
                deletedAt: null,
            },
            {
                id: 3,
                code: "KHUYENTAI",
                name: "Khuyên tai lấp lánh",
                images: "https://cdn.pnj.io/images/thumbnails/300/300/detailed/192/sp-gnxmxmw004435-nhan-vang-14k-dinh-da-ecz-disney-pnj-general-disney-princess-d100-1.png",
                origin: "VN",
                material: "Kim cương",
                size: "nhỏ 4x6",
                warranty: "1 năm",
                description: "Khuyên tai lấp lánh phù hợp cho mọi lứa tuổi",
                price: 10,
                categoryId: 1,
                quantity: 10,
                discountId: 0,
            },
            {
                id: 2,
                code: "KHUYENTAI",
                name: "Khuyên tai lấp lánh",
                images: "https://cdn.pnj.io/images/thumbnails/300/300/detailed/192/sp-gnxmxmw004434-nhan-vang-14k-dinh-da-ecz-disney-pnj-snow-white-the-seven-dwarfs-d100-1.png",
                origin: "VN",
                material: "Kim cương",
                size: "nhỏ 4x6",
                warranty: "1 năm",
                description: "Khuyên tai lấp lánh phù hợp cho mọi lứa tuổi",
                price: 10,
                categoryId: 1,
                quantity: 10,
                discountId: 0,
            },
        ],
    },
    {
        name: "khuyến mãi",
        id: 5,
        banner: "https://cdn.pnj.io/images/promo/191/day-chuyen-t11-1200x450-CTA.jpg",
        src: "https://cdn.pnj.io/images/thumbnails/300/300/detailed/193/sp-glxmxmy000993-lac-tay-vang-14k-dinh-da-cz-pnj-01.png",
        product: [
            {
                id: 9,
                name: "Dây chuyền kim cương",
                code: "DAYCHUYEN003",
                images: "https://cdn.pnj.io/images/thumbnails/300/300/detailed/193/sp-gbxmxmy006144-bong-tai-vang-14k-dinh-da-cz-pnj-01.png",
                origin: "USA",
                material: "Kim cương",
                size: "40cm",
                warranty: "Lifetime",
                description: "Dây chuyền kim cương cao cấp, bền vững.",
                price: 499,
                category: "Dây chuyền",
                inventory: 5,
                createdAt: "2023-11-30T21:51:36.000Z",
                updatedAt: "2023-11-30T21:51:36.000Z",
                deletedAt: null,
            },
            {
                id: 1,
                name: "Vòng tay đá xanh",
                code: "VONGTAY001",
                images: "https://cdn.pnj.io/images/thumbnails/300/300/detailed/193/sp-glxmxmy000993-lac-tay-vang-14k-dinh-da-cz-pnj-01.png",
                origin: "Vietnam",
                material: "Đá",
                size: "Free size",
                warranty: "6 months",
                description: "Vòng tay đá xanh dành cho mọi lứa tuổi.",
                price: 25,
                category: "Vòng tay",
                inventory: 1,
                createdAt: "2023-11-30T21:51:36.000Z",
                updatedAt: "2023-11-30T21:51:36.000Z",
                deletedAt: null,
            },
            {
                id: 7,
                name: "Dây chuyền vàng hồng",
                code: "DAYCHUYEN001",
                images: "https://cdn.pnj.io/images/thumbnails/300/300/detailed/193/sp-glxmxmy000997-lac-tay-vang-14k-dinh-da-cz-pnj-01.png",
                origin: "France",
                material: "Vàng hồng 14K",
                size: "45cm",
                warranty: "1 year",
                description: "Dây chuyền vàng hồng 14K đẳng cấp.",
                price: 149,
                category: "Dây chuyền",
                inventory: 75,
                createdAt: "2023-11-30T21:51:36.000Z",
                updatedAt: "2023-11-30T21:51:36.000Z",
                deletedAt: null,
            },
            {
                id: 6,
                code: "KHUYENTAI",
                name: "Khuyên tai lấp lánh",
                images: "https://cdn.pnj.io/images/thumbnails/300/300/detailed/192/sp-gcxmxmw000391-day-co-vang-14k-dinh-da-ecz-disney-pnj-snow-white-the-seven-dwarfs-d100-1.png",
                origin: "VN",
                material: "Kim cương",
                size: "nhỏ 4x6",
                warranty: "1 năm",
                description: "Khuyên tai lấp lánh phù hợp cho mọi lứa tuổi",
                price: 10,
                categoryId: 1,
                quantity: 10,
                discountId: 0,
            },
            {
                id: 5,
                name: "Dây chuyền kim cương",
                code: "DAYCHUYEN003",
                images: "https://cdn.pnj.io/images/thumbnails/300/300/detailed/193/sp-gbxmxmy006144-bong-tai-vang-14k-dinh-da-cz-pnj-01.png",
                origin: "USA",
                material: "Kim cương",
                size: "40cm",
                warranty: "Lifetime",
                description: "Dây chuyền kim cương cao cấp, bền vững.",
                price: 499,
                category: "Dây chuyền",
                inventory: 5,
                createdAt: "2023-11-30T21:51:36.000Z",
                updatedAt: "2023-11-30T21:51:36.000Z",
                deletedAt: null,
            },
            {
                id: 4,
                name: "Vòng tay đá xanh",
                code: "VONGTAY001",
                images: "https://cdn.pnj.io/images/thumbnails/300/300/detailed/193/sp-glxmxmy000993-lac-tay-vang-14k-dinh-da-cz-pnj-01.png",
                origin: "Vietnam",
                material: "Đá",
                size: "Free size",
                warranty: "6 months",
                description: "Vòng tay đá xanh dành cho mọi lứa tuổi.",
                price: 25,
                category: "Vòng tay",
                inventory: 1,
                createdAt: "2023-11-30T21:51:36.000Z",
                updatedAt: "2023-11-30T21:51:36.000Z",
                deletedAt: null,
            },
            {
                id: 8,
                name: "Dây chuyền vàng hồng",
                code: "DAYCHUYEN001",
                images: "https://cdn.pnj.io/images/thumbnails/300/300/detailed/192/sp-gv0000w060419-vong-tay-vang-trang-y-18k-pnj-1.png",
                origin: "France",
                material: "Vàng hồng 14K",
                size: "45cm",
                warranty: "1 year",
                description: "Dây chuyền vàng hồng 14K đẳng cấp.",
                price: 149,
                category: "Dây chuyền",
                inventory: 75,
                createdAt: "2023-11-30T21:51:36.000Z",
                updatedAt: "2023-11-30T21:51:36.000Z",
                deletedAt: null,
            },
            {
                id: 3,
                code: "KHUYENTAI",
                name: "Khuyên tai lấp lánh",
                images: "https://cdn.pnj.io/images/thumbnails/300/300/detailed/192/sp-gnxmxmw004435-nhan-vang-14k-dinh-da-ecz-disney-pnj-general-disney-princess-d100-1.png",
                origin: "VN",
                material: "Kim cương",
                size: "nhỏ 4x6",
                warranty: "1 năm",
                description: "Khuyên tai lấp lánh phù hợp cho mọi lứa tuổi",
                price: 10,
                categoryId: 1,
                quantity: 10,
                discountId: 0,
            },
            {
                id: 2,
                code: "KHUYENTAI",
                name: "Khuyên tai lấp lánh",
                images: "https://cdn.pnj.io/images/thumbnails/300/300/detailed/192/sp-gnxmxmw004434-nhan-vang-14k-dinh-da-ecz-disney-pnj-snow-white-the-seven-dwarfs-d100-1.png",
                origin: "VN",
                material: "Kim cương",
                size: "nhỏ 4x6",
                warranty: "1 năm",
                description: "Khuyên tai lấp lánh phù hợp cho mọi lứa tuổi",
                price: 10,
                categoryId: 1,
                quantity: 10,
                discountId: 0,
            },
        ],
    },
    {
        name: "mới",
        id: 6,
        banner: "https://cdn.pnj.io/images/promo/194/Tabsale_Style_t12_1200x450-CTA.png",
        src: "https://cdn.pnj.io/images/thumbnails/300/300/detailed/193/sp-glxmxmy000993-lac-tay-vang-14k-dinh-da-cz-pnj-01.png",
        product: [
            {
                id: 9,
                name: "Dây chuyền kim cương",
                code: "DAYCHUYEN003",
                images: "https://cdn.pnj.io/images/thumbnails/300/300/detailed/193/sp-gbxmxmy006144-bong-tai-vang-14k-dinh-da-cz-pnj-01.png",
                origin: "USA",
                material: "Kim cương",
                size: "40cm",
                warranty: "Lifetime",
                description: "Dây chuyền kim cương cao cấp, bền vững.",
                price: 499,
                category: "Dây chuyền",
                inventory: 5,
                createdAt: "2023-11-30T21:51:36.000Z",
                updatedAt: "2023-11-30T21:51:36.000Z",
                deletedAt: null,
            },
            {
                id: 1,
                name: "Vòng tay đá xanh",
                code: "VONGTAY001",
                images: "https://cdn.pnj.io/images/thumbnails/300/300/detailed/193/sp-glxmxmy000993-lac-tay-vang-14k-dinh-da-cz-pnj-01.png",
                origin: "Vietnam",
                material: "Đá",
                size: "Free size",
                warranty: "6 months",
                description: "Vòng tay đá xanh dành cho mọi lứa tuổi.",
                price: 25,
                category: "Vòng tay",
                inventory: 1,
                createdAt: "2023-11-30T21:51:36.000Z",
                updatedAt: "2023-11-30T21:51:36.000Z",
                deletedAt: null,
            },
            {
                id: 7,
                name: "Dây chuyền vàng hồng",
                code: "DAYCHUYEN001",
                images: "https://cdn.pnj.io/images/thumbnails/300/300/detailed/193/sp-glxmxmy000997-lac-tay-vang-14k-dinh-da-cz-pnj-01.png",
                origin: "France",
                material: "Vàng hồng 14K",
                size: "45cm",
                warranty: "1 year",
                description: "Dây chuyền vàng hồng 14K đẳng cấp.",
                price: 149,
                category: "Dây chuyền",
                inventory: 75,
                createdAt: "2023-11-30T21:51:36.000Z",
                updatedAt: "2023-11-30T21:51:36.000Z",
                deletedAt: null,
            },
            {
                id: 6,
                code: "KHUYENTAI",
                name: "Khuyên tai lấp lánh",
                images: "https://cdn.pnj.io/images/thumbnails/300/300/detailed/192/sp-gcxmxmw000391-day-co-vang-14k-dinh-da-ecz-disney-pnj-snow-white-the-seven-dwarfs-d100-1.png",
                origin: "VN",
                material: "Kim cương",
                size: "nhỏ 4x6",
                warranty: "1 năm",
                description: "Khuyên tai lấp lánh phù hợp cho mọi lứa tuổi",
                price: 10,
                categoryId: 1,
                quantity: 10,
                discountId: 0,
            },
            {
                id: 5,
                name: "Dây chuyền kim cương",
                code: "DAYCHUYEN003",
                images: "https://cdn.pnj.io/images/thumbnails/300/300/detailed/193/sp-gbxmxmy006144-bong-tai-vang-14k-dinh-da-cz-pnj-01.png",
                origin: "USA",
                material: "Kim cương",
                size: "40cm",
                warranty: "Lifetime",
                description: "Dây chuyền kim cương cao cấp, bền vững.",
                price: 499,
                category: "Dây chuyền",
                inventory: 5,
                createdAt: "2023-11-30T21:51:36.000Z",
                updatedAt: "2023-11-30T21:51:36.000Z",
                deletedAt: null,
            },
            {
                id: 4,
                name: "Vòng tay đá xanh",
                code: "VONGTAY001",
                images: "https://cdn.pnj.io/images/thumbnails/300/300/detailed/193/sp-glxmxmy000993-lac-tay-vang-14k-dinh-da-cz-pnj-01.png",
                origin: "Vietnam",
                material: "Đá",
                size: "Free size",
                warranty: "6 months",
                description: "Vòng tay đá xanh dành cho mọi lứa tuổi.",
                price: 25,
                category: "Vòng tay",
                inventory: 1,
                createdAt: "2023-11-30T21:51:36.000Z",
                updatedAt: "2023-11-30T21:51:36.000Z",
                deletedAt: null,
            },
            {
                id: 8,
                name: "Dây chuyền vàng hồng",
                code: "DAYCHUYEN001",
                images: "https://cdn.pnj.io/images/thumbnails/300/300/detailed/192/sp-gv0000w060419-vong-tay-vang-trang-y-18k-pnj-1.png",
                origin: "France",
                material: "Vàng hồng 14K",
                size: "45cm",
                warranty: "1 year",
                description: "Dây chuyền vàng hồng 14K đẳng cấp.",
                price: 149,
                category: "Dây chuyền",
                inventory: 75,
                createdAt: "2023-11-30T21:51:36.000Z",
                updatedAt: "2023-11-30T21:51:36.000Z",
                deletedAt: null,
            },
            {
                id: 3,
                code: "KHUYENTAI",
                name: "Khuyên tai lấp lánh",
                images: "https://cdn.pnj.io/images/thumbnails/300/300/detailed/192/sp-gnxmxmw004435-nhan-vang-14k-dinh-da-ecz-disney-pnj-general-disney-princess-d100-1.png",
                origin: "VN",
                material: "Kim cương",
                size: "nhỏ 4x6",
                warranty: "1 năm",
                description: "Khuyên tai lấp lánh phù hợp cho mọi lứa tuổi",
                price: 10,
                categoryId: 1,
                quantity: 10,
                discountId: 0,
            },
            {
                id: 2,
                code: "KHUYENTAI",
                name: "Khuyên tai lấp lánh",
                images: "https://cdn.pnj.io/images/thumbnails/300/300/detailed/192/sp-gnxmxmw004434-nhan-vang-14k-dinh-da-ecz-disney-pnj-snow-white-the-seven-dwarfs-d100-1.png",
                origin: "VN",
                material: "Kim cương",
                size: "nhỏ 4x6",
                warranty: "1 năm",
                description: "Khuyên tai lấp lánh phù hợp cho mọi lứa tuổi",
                price: 10,
                categoryId: 1,
                quantity: 10,
                discountId: 0,
            },
        ],
    },
];

const ShowCatalogCard = () => {
    return (
        <ul className="flex flex-row w-full h-full item-center justify-around">
            {catagories.map((catalog) => {
                return (
                    <li
                        key={catalog.id}
                        className="w-60 h-60 p-2 m-6 shadow-lg "
                    >
                        <CatalogList
                            images={catalog.src}
                            name={catalog.name}
                            button="shop now"
                        />
                    </li>
                );
            })}
        </ul>
    );
};

export default ShowCatalogCard;
